# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5da1c0b7fd939a7049c97fd006218875e1d0007ab610aeed70e323763fdededa52fe375b75356894d4ad7036a154008fc1fcae11040f7e17f978bd45d74dfe61

test:
  secret_key_base: f97b24ccda67b1208a51e3642bc320823221092c682a78c2d0493b28e68412628f496d6ebdff13a7fe85b0b534cf53d6c8ef8ce5552c031fc7b6ae2fe5c21fe5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
